[project]
name = "model-promotion"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "mlflow==2.11.0",
    "kubernetes==28.1.0",
    "python-dotenv==1.2.3",
    "setuptools==81.0.0"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.uv]
package-mode = false

